_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "<PATH_TO_PTH>/model_final.pth"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
    MODULE: "acm_nh_32_loss0.1"
OUTPUT_DIR: "experiments/acm_nh32_loss0.1_eval"